#! /bin/bash

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="NGINX CONFIG";
TASK_NAME=$DOMAIN;

CONF_PATH="$SITES/$DOMAIN.conf"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# CREATE STRUCTURE IF NEEDED

echo "- Check NGINX conf file:";
echo "-";
if [ -d $CONF_PATH ]
then
  rm -rf $CONF_PATH && echo "- ✅ Removed existing conf file";
fi

echo "- Create $DOMAIN conf file:";
echo "-";

echo "server {
  listen 80;
  listen [::]:80;

  root /var/www/$DOMAIN/www;
  index index.html;

  server_name $DOMAIN;

  location / {
    try_files \$uri \$uri/ =404;
  }
}" > $CONF_PATH && echo "- ✅ Created conf file";

echo ""
echo "= $TASK_TYPE COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++