#! /bin/bash

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="CREATE";
TASK_NAME="WORDPRESS SITE";

export WP_PATH="$HABITAT_WWW/php8/wp"
export DOMAIN="$1.dev.traaidmark.com"
export REPO="$2"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo "++ Type: Wordpress"
echo "++ Domain: $DOMAIN"
echo "++ Repository: $REPO"
echo "++ Domain: $PROJECT"
echo "+"
echo ""

# CREATE STRUCTURE IF NEEDED

# ./bin/wp-tasks/project-init $1 $2
# ./bin/wp-tasks/core-get
# ./bin/wp-tasks/scaffold-core $1
# ./bin/wp-tasks/fresh-install $1

# ./bin/wp-tasks/install-default-stack $1

# ./bin/wp-tasks/update-core $1
# ./bin/wp-tasks/update-plugins $1
# ./bin/wp-tasks/update-themes $1

# ./bin/wp-tasks/copy-robots-file $1

# ./bin/nginx-tasks/register-wp-site $1

echo "- Do Stuff:";
echo "-";

echo "- ✅ Result";

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
