#! /bin/bash

# 1. FRESH INSTALL +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Default Stack Install"
echo ""
echo "---"
echo ""

local_project_dir=$PWD/www/php8/wp/$1.dev.traaidmark.com
docker_project_dir=./$1.dev.traaidmark.com/www

core_plugins="contact-form-7 slim-seo ultimate-addons-for-gutenberg"

optional_plugins="shortpixel-image-optimiser custom-post-type-ui all-in-one-schemaorg-rich-snippets litespeed-cache"

cp -a ./assets/wp-themes/. $local_project_dir/www/wp-content/themes/
cp -a ./assets/wp-plugins/. $local_project_dir/www/wp-content/plugins/

rm -rf $local_project_dir/www/wp-content/plugins/hello.php;

# docker compose run --rm wpcli theme install $theme_astra  --path="$docker_project_dir";

docker compose run --rm wpcli theme activate astra --path="$docker_project_dir";

docker compose run --rm wpcli plugin install $core_plugins $optional_plugins  --path="$docker_project_dir";

docker compose run --rm wpcli plugin activate $core_plugins astra-addon --path="$docker_project_dir";



# docker compose run --rm wpcli plugin install all-in-one-schemaorg-rich-snippets ultimate-addons-for-gutenberg  --path="$docker_project_dir";

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++