#! /bin/bash

# 1. UPDATE CORE +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Updating Wordpress Core"
echo ""
echo "---"
echo ""

docker_project_dir=./$1.dev.traaidmark.com/www

docker compose run --rm wpcli core update --path="$docker_project_dir";

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++