#! /bin/bash

# 1. UPDATE PLUGINS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Updating Wordpress Core"
echo ""
echo "---"
echo ""

docker_project_dir=./$1.dev.traaidmark.com/www

docker compose run --rm wpcli plugin update --all --path="$docker_project_dir";

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++