#! /bin/bash

# 1. UPDATE THEMES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Updating Wordpress Themes"
echo ""
echo "---"
echo ""

docker_project_dir=./$1.dev.traaidmark.com/www

docker compose run --rm wpcli theme update --all --path="$docker_project_dir";

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++