#! /bin/bash

# 1. SETUP WORK DIRECTORY ++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "- Initialize Wordpress project";
echo "-";

echo "- ✅ Result";

project_dir=./www/php8/wp/$1.dev.traaidmark.com

workbook_dir=./www/php8/wp/$1.dev.traaidmark.com/_workbook
bin_dir=./www/php8/wp/$1.dev.traaidmark.com/_bin

[ -d $project_dir ] && rm -rf $project_dir;

if [ -z "$2" ]
then
  echo "Init mode: local only"
  mkdir $project_dir;
else
  echo "Init mode: from repository"
  git clone $2 $project_dir;
fi

[ ! -d $workbook_dir ] && mkdir $workbook_dir && touch $workbook_dir/.gitignore;
[ ! -d $bin_dir ] && mkdir $bin_dir && touch $bin_dir/.gitignore;
[ ! -d $bin_dir/databases ] && mkdir $bin_dir/databases && touch $bin_dir/databases/.gitignore;

echo "✅ Created project structure!"

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
