#! /bin/bash

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="SETUP";
TASK_NAME="INITIAL STRUCTURE";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. SETUP HABITAT DIRS ------------------------------------------------------

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

echo "- Scaffolding paths";
echo "-";

[ ! -d $SYS_HABITAT ] && mkdir $SYS_HABITAT && echo "- ✅ Create Habitat directory";
[ ! -d $SYS_HABITAT/logs ] && mkdir $SYS_HABITAT/logs && echo "- ✅ Create logs directory";
[ ! -d $SYS_HABITAT/nginx ] && mkdir $SYS_HABITAT/nginx && echo "- ✅ Create Nginx directory";
[ ! -d $SYS_HABITAT/nginx/sites ] && mkdir $SYS_HABITAT/nginx/sites && echo "- ✅ Create Nginx Sites directory";
[ ! -d $HABITAT_WWW ] && mkdir $HABITAT_WWW && echo "- ✅ Create www directory";

echo ""
echo "= $TASK_NAME COMPLETE"
echo ""

# 2.1. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++