#! /bin/bash

# 1. CACHE SETUP +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Downloading Wordpress Core"
echo ""
echo "---"
echo ""

wp_cache_dir=".wp-cache"

[ ! -d $wp_cache_dir ] && mkdir $wp_cache_dir && docker compose run --rm wpcli core download --path="$wp_cache_dir";

[ -d $wp_cache_dir ] && echo "Wordpress cache exists! - Skipping"

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++