#! /bin/bash

# 1. SETUP WORK DIRECTORY ++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Copying default landing page"
echo ""
echo "---"
echo ""

project_dir=./www/static/$1.dev.traaidmark.com

[ ! -d $project_dir/www ] && mkdir $project_dir/www && cp $PWD/assets/static/index.html $project_dir/www/index.html;

echo "✅ Created default page"

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
