#! /bin/bash

# 1. SETUP WORK DIRECTORY ++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Creating Static project for: $1"
echo ""
echo "---"
echo ""

project_dir=./www/static/$1.dev.traaidmark.com

workbook_dir=./www/static/$1.dev.traaidmark.com/_workbook

[ -d $project_dir ] && rm -rf $project_dir;

if [ -z "$2" ]
then
  echo "Init mode: local only"
  mkdir $project_dir;
else
  echo "Init mode: from repository"
  git clone $2 $project_dir;
fi

[ ! -d $workbook_dir ] && mkdir $workbook_dir && touch $workbook_dir/.gitignore;

echo "✅ Created project structure!"

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
