#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="CACHE";
TASK_NAME="Wordpress";

WP_CACHE="$_CACHE/wordpress";
WP_PLUGINS="$WP_CACHE/wp-content/plugins";
WP_THEMES="$WP_CACHE/wp-content/themes";


BOX_THEMES="$_BOX/wordpress/themes";
BOX_PLUGINS="$_BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# 2.1. CREATE WORDPRESS CACHE --------------------------------------------------

# CHECK WP DIR

echo "- Verify cache folder";

if [ -d $WP_CACHE ]
then
  echo "-- ✅ Wordpress root folder exists";
else
  mkdir $WP_CACHE && echo "-- ✅ Create Wordpress cache folder";
fi

# 2.1. END ---------------------------------------------------------------------

# 2.2. DOWNLOAD CORE -----------------------------------------------------------

echo "- Download Wordpress Core";

wp core download --path="$WP_CACHE" && echo "-- ✅ Downloaded Wordpress core";

# 2.2. END ---------------------------------------------------------------------

# 2.3. COPY STACK --------------------------------------------------------------

# COPY WP THEMES

echo "- Scaffold Wordpress Stack";

cp -r $BOX_THEMES/. $WP_THEMES  && echo "-- ✅ Copied Wordpress themes from Box";
cp -r $BOX_PLUGINS/. $WP_PLUGINS  && echo "-- ✅ Copied Wordpress plugins from Box";

# 2.3. END ---------------------------------------------------------------------

# 2.4. CLEAN UP ----------------------------------------------------------------

echo "- Clean up";
rm -rf $WP_PLUGINS/hello.php  && echo "-- ✅ Removed unrequired files from Wordpress cache.";

# 2.4. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++