#! /bin/bash

# Available system vars:
# HABITAT_DATABASE_USER
# HABITAT_DATABASE_PASSWORD
# HABITAT_DATABASE_ROOT_PASSWORD

# HABITAT_WP_ADMIN_USER
# HABITAT_WP_ADMIN_PASSWORD
# HABITAT_WP_ADMIN_EMAIL

# HABITAT_SITES="$HOME/sites"
# HABITAT_WWW="$HOME/www"
# HABITAT_BOX="$HOME/.assets/box"
# HABITAT_CACHE="$HOME/.assets/cache"

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="CREATE";
TASK_NAME="WORDPRESS CACHE";

WP_CACHE="$HABITAT_CACHE/wordpress";
WP_PLUGINS="$WP_CACHE/wp-content/plugins";
WP_THEMES="$WP_CACHE/wp-content/themes";


BOX_THEMES="$HABITAT_BOX/wordpress/themes";
BOX_PLUGINS="$HABITAT_BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# 2.1. CREATE WORDPRESS CACHE --------------------------------------------------

# CHECK WP DIR

echo "- Verify cache folder";

if [ -d $WP_CACHE ]
then
  echo "-- ✅ Wordpress root folder exists";
else
  mkdir $WP_CACHE && echo "-- ✅ Create Wordpress cache folder";
fi

# 2.1. END ---------------------------------------------------------------------

# 2.2. DOWNLOAD CORE -----------------------------------------------------------

echo "- Download Wordpress Core";

wp --path="$WP_CACHE" && echo "-- ✅ Downloaded Wordpress core";

# 2.2. END ---------------------------------------------------------------------

# 2.3. COPY STACK --------------------------------------------------------------

# COPY WP THEMES

echo "- Scaffold Wordpress Stack";

cp -r $BOX_THEMES/. $WP_THEMES  && echo "-- ✅ Copied Wordpress themes from Box";
cp -r $BOX_PLUGINS/. $WP_PLUGINS  && echo "-- ✅ Copied Wordpress plugins from Box";

# 2.3. END ---------------------------------------------------------------------

# 2.4. CLEAN UP ----------------------------------------------------------------

echo "- Clean up";
rm -rf $WP_THEMES/hello.php  && echo "-- ✅ Removed unrequired files from Wordpress cache.";

# 2.4. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++