#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"


# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

export TYPE="$1"
export TYPE_PATH="$WWW";

if [ $TYPE = "wordpress" ]
then
  export TYPE_PATH="$WWW/php8/wordpress"
fi

export DOMAIN="$2.dev.traaidmark.com"
export PROJECT_PATH="$TYPE_PATH/$DOMAIN"
export PROJECT_WWW="$TYPE_PATH/$DOMAIN/www"

if [ -z $3 ]
then
  export PROJECT_MODE="local"
else
  export PROJECT_REPO="$3"
  export PROJECT_MODE="repository"
fi

TASK_TYPE="CREATE SITE";
TASK_NAME="[$TYPE] $DOMAIN";

# WP_CACHE="$WP_PATH/_cache";
# WP_PLUGINS="$WP_CACHE/wp-content/plugins";
# WP_THEMES="$WP_CACHE/wp-content/themes";

# BOX_THEMES="$BOX/wordpress/themes";
# BOX_PLUGINS="$BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo "++ Type: $TYPE"
echo "++ Mode: $PROJECT_MODE"
[ ! -z $PROJECT_REPO ] && echo "++ Repository Url: $PROJECT_REPO";
echo "++ Domain: $DOMAIN"
echo "++ Root: $PROJECT_PATH"
echo "+"
echo ""

# 2.1. MAKE PROJECT ------------------------------------------------------------

util-make-project;

# 2.1. END ---------------------------------------------------------------------

# 2.2. COPY CACHE --------------------------------------------------------------

[ $TYPE = "wordpress" ]util-copy-wordpress-cache;

# 2.2. END ---------------------------------------------------------------------

# 2.3. COPY DEV ROBOTS FILE ----------------------------------------------------

util-copy-dev-robots;

# 2.3. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 3. POST CALLS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# nginx-make-wordpress-site;

# 3. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++