#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"


# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

export PROJECT_TYPE="$1"
export DOMAIN="$2.dev.traaidmark.com"

export PROJECT_PATH="$WWW";

if [ $PROJECT_TYPE = "wordpress" ]
then
  export PROJECT_PATH="$WWW/php8/wordpress"
fi

export PROJECT_WWW="$DOMAIN/www";

if [ -z $3 ]
then
  export PROJECT_MODE="local"
else
  export PROJECT_REPO="$3"
  export PROJECT_MODE="repository"
fi

TASK_TYPE="CREATE SITE";
TASK_NAME="[$PROJECT_TYPE] $DOMAIN";

export WWW_PATH="$WWW/php8/wordpress";

# WP_CACHE="$WP_PATH/_cache";
# WP_PLUGINS="$WP_CACHE/wp-content/plugins";
# WP_THEMES="$WP_CACHE/wp-content/themes";

# BOX_THEMES="$BOX/wordpress/themes";
# BOX_PLUGINS="$BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo "++ Type: $PROJECT_TYPE"
echo "++ Mode: $PROJECT_MODE"
[ ! -z $PROJECT_REPO ] && echo "++ Repository Url: $PROJECT_REPO";
echo "++ Domain: $DOMAIN"
echo "++ Root: $PROJECT_WWW"
echo "+"
echo ""

# 2.1. MAKE PROJECT ------------------------------------------------------------

echo $WWW_PATH;

util-make-project;

# 2.1. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 3. POST CALLS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# nginx-make-wordpress-site;

# 3. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++