#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# CMD: create-site $ENV $STACK $NAME $REPO
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

export ENV="$1"
export STACK="$2"
export NAME="$3"
export REPO="$4"

# BUILD SITE VARS

export DOMAIN="$NAME.$ENV.traaidmark.com"
export SITE_PATH="$_SITES/$DOMAIN"
export SITE_ROOT="$SITE_PATH/www"

if [ -z $4 ]
then
  export SITE_MODE="Local"
else
  export SITE_REPO="$REPO"
  export SITE_MODE="Repository"
fi

# BUILD ENV VARS

# BUILD STACK VARS
# # BUILD SITE VARS

# export TYPE_PATH="$WWW";

# if [ $TYPE = "wordpress" ]
# then
#   export TYPE_PATH="$WWW/php8/wordpress"
# fi

# export PROJECT_PATH="$TYPE_PATH/$DOMAIN"
# export PROJECT_WWW="$TYPE_PATH/$DOMAIN/www"



TASK_TYPE="CREATE";
TASK_NAME="[$STACK] $DOMAIN";

# WP_CACHE="$WP_PATH/_cache";
# WP_PLUGINS="$WP_CACHE/wp-content/plugins";
# WP_THEMES="$WP_CACHE/wp-content/themes";

# BOX_THEMES="$BOX/wordpress/themes";
# BOX_PLUGINS="$BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo "++ Environment: $ENV"
echo "++ Stack: $STACK"
echo "++ Site:"
echo "++ Domain: $DOMAIN"
echo "++ Mode: $SITE_MODE"
[ ! -z $SITE_REPO ] && echo "++ Repository Url: $SITE_REPO";
echo "+"
echo ""

# 2.1. CREATE SITE -------------------------------------------------------------

util-create-site;

# 2.1. END ---------------------------------------------------------------------

# 2.3. APPLY STACK CACHE -------------------------------------------------------

[ $STACK = "wordpress" ] && util-apply-wordpress-cache;

# 2.3. END ---------------------------------------------------------------------

# 2.3. APPLY DEV META ----------------------------------------------------------

[ $ENV = "dev" ] && util-apply-dev-meta;

# 2.3. END ---------------------------------------------------------------------

# 2.4. WORDPRESS TASKS ---------------------------------------------------------

# CONFIG

util-wordpress-config

# DATABASE

# INSTALL

# 2.4. END ---------------------------------------------------------------------

# 2.5. BACKUP ------------------------------------------------------------------



# 2.5. END ---------------------------------------------------------------------

# 2.6. COMMIT ------------------------------------------------------------------

# ./util-git-commit "initial project scaffold";

# 2.6. END ---------------------------------------------------------------------

# 2.7. APPLY SERVER ------------------------------------------------------------

# 2.7. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++