#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"


# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="CACHE";
TASK_NAME="WORDPRESS STACK";

export PROJECT_TYPE="wordpress"


export WWW_PATH="$WWW/php8/wordpress";

# WP_CACHE="$WP_PATH/_cache";
# WP_PLUGINS="$WP_CACHE/wp-content/plugins";
# WP_THEMES="$WP_CACHE/wp-content/themes";

# BOX_THEMES="$BOX/wordpress/themes";
# BOX_PLUGINS="$BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""



echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 3. POST CALLS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

nginx-make-wordpress-site;

# 3. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++