#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"


# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

export PROJECT_TYPE="wordpress"
export DOMAIN="$1.dev.traaidmark.com"
export PROJECT_PATH="$WWW/php8/wordpress/$DOMAIN";
export PROJECT_WWW="$PROJECT_PATH/www";

if [ -z $2 ]
then
  export PROJECT_MODE="local"
else
  export PROJECT_REPO="$2"
  export PROJECT_MODE="repository"
fi

TASK_TYPE="CREATE SITE";
TASK_NAME="[WORDPRESS] ";

export WWW_PATH="$WWW/php8/wordpress";

# WP_CACHE="$WP_PATH/_cache";
# WP_PLUGINS="$WP_CACHE/wp-content/plugins";
# WP_THEMES="$WP_CACHE/wp-content/themes";

# BOX_THEMES="$BOX/wordpress/themes";
# BOX_PLUGINS="$BOX/wordpress/plugins";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo "++ Type: $PROJECT_TYPE"
echo "++ Mode: $PROJECT_MODE"
[ ! -z $PROJECT_REPO ] && echo "++ Repository Url: $PROJECT_REPO";
echo "++ Domain: $DOMAIN"
echo "++ Root: $PROJECT_WWW"
echo "+"
echo ""



echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 3. POST CALLS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# nginx-make-wordpress-site;

# 3. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++