#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# CMD: create-site $ENV $STACK $NAME $REPO
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

export ENV="dev"
export STACK="wordpress"
export NAME="$1"
export WWW="/var/www/dev/wordpress"

# BUILD SITE VARS

export DOMAIN="$NAME.$ENV.traaidmark.com"
export PROJECT_PATH="$WWW/$DOMAIN"
export SITE_ROOT="$PROJECT_PATH/www"

if [ -z $2 ]
then
  export SITE_MODE="Local"
else
  export SITE_REPO="$2"
  export SITE_MODE="Repository"
fi

# BUILD PROCESS VARS

DIR_META="$_BOX/dev-meta"

# BUILD ENV VARS

TASK_TYPE="CREATE";
TASK_NAME="[$STACK] $DOMAIN";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo "++ Environment: $ENV"
echo "++ Stack: $STACK"
echo "++ Site:"
echo "++ Domain: $DOMAIN"
echo "++ Path: $SITE_ROOT"
echo "++ Mode: $SITE_MODE"
[ ! -z $SITE_REPO ] && echo "++ Repository Url: $SITE_REPO";
echo "+"
echo ""

# 2.1. CREATE SITE -------------------------------------------------------------

# 2.1.1. CLEAN INSTALL

echo "- 🤠 Clean existing installs";

if [ -d $PROJECT_PATH ]
then
  rm -rf $PROJECT_PATH && echo "-- ✅ Removed $PROJECT_PATH";
  
else 
  echo "-- ✅ This is a clean install!";
fi

# 2.1.1. END

# 2.1.2. CLONE REPOSITORY

echo "- 🤠 Creating project from new repository";
  git clone $SITE_REPO $PROJECT_PATH && echo "-- ✅ Cloned site into $PROJECT_PATH!";

# 2.1.2. END

# 2.1.3. TODO: ADD ERROR CHECKING FOR FOLDER STRUCTURE
# 2.1.3. END

# 2.1. END ---------------------------------------------------------------------

# 2.3. APPLY DEV META ----------------------------------------------------------

echo "- 🤠 Apply dev meta";

cp -r $DIR_META/. $SITE_ROOT && echo "-- ✅ Copied dev meta files";

# 2.3. END ---------------------------------------------------------------------

# 2.4. WORDPRESS TASKS ---------------------------------------------------------

# CONFIG

# util-wordpress-config

# DATABASE

# util-wordpress-db-create

# INSTALL

# util-wordpress-install

# 2.4. END ---------------------------------------------------------------------

# 2.5. BACKUP ------------------------------------------------------------------



# 2.5. END ---------------------------------------------------------------------

# 2.6. COMMIT ------------------------------------------------------------------

# ./util-git-commit "initial project scaffold";

# 2.6. END ---------------------------------------------------------------------

# 2.7. APPLY TO WWW ------------------------------------------------------------

# ln -s $SITE_ROOT $PROJECT_PATH && echo "-- ✅ Linked www to server";

# 2.7. END ---------------------------------------------------------------------

# 2.8. REGISTER SITE -----------------------------------------------------------

# util-nginx-register;

# util-nginx-apply;

# server-nginx restart;

# 2.8. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++