#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="CREATE";
TASK_NAME="Server Environment";

BOX_REPO="git@github.com:traaidmark/trm-habitat-box.git"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# 2.1. WEB ENV -----------------------------------------------------------------

echo "- Create web environment";
[ ! -d $_WWW ] && ln -s $_ROOT_WWW $_WWW &&  echo "-- ✅ Created a symlink from www to Habitat";
[ ! -d $_WWW_DEV ] && mkdir $_WWW_DEV &&  echo "-- ✅ Created dev environment";
[ ! -d $_WWW_PROD ] && mkdir $_WWW_PROD &&  echo "-- ✅ Created production environment";

# 2.1. END ---------------------------------------------------------------------

# 2.2. CREATE SITES ------------------------------------------------------------

echo "- Create sites environment";
[ ! -d $_SITES ] && mkdir $_SITES &&  echo "-- ✅ Created sites environment";
[ ! -d $_SITE_CONF ] && mkdir $_SITE_CONF &&  echo "-- ✅ Created site config directory";

# 2.2. END ---------------------------------------------------------------------

# 2.3. CREATE BOX --------------------------------------------------------------

echo "- Create Box";

[ ! -d $_BOX ] && git clone $BOX_REPO $_BOX &&  echo "-- ✅ Created Box";

# 2.3. END ---------------------------------------------------------------------

# 2.4. CREATE CACHE ------------------------------------------------------------

echo "- Create Cache";
[ ! -d $_CACHE ] && mkdir $_CACHE &&  echo "-- ✅ Created cache directory";

# 2.4. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++