#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="CREATE";
TASK_NAME="ADMINER";

export DOMAIN="db.ops.traaidmark.com"
export SITE_PATH="$_SITES/$DOMAIN";
export SITE_ROOT="$_SITES/$DOMAIN/www";

ADMINER_PATH="$_BOX/adminer"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# 2.1. CREATE SITE -------------------------------------------------------------

echo "- Create site";
[ ! -d $_SITES/$DOMAIN ] && cp -r $ADMINER_PATH  && $SITE_PATH echo "-- ✅ Applied adminer to sites";

# 2.1. END ---------------------------------------------------------------------

# 2.2. ADD TO WWW --------------------------------------------------------------

[ ! -d $_WWW/$DOMAIN ] && ln -s $_SITES/$SITE_ROOT $_WWW/$DOMAIN  &&  echo "-- ✅ Linked www to server";

# 2.2. END ---------------------------------------------------------------------

# 2.3. REGISTER SITE -----------------------------------------------------------

util-nginx-register-adminer;

# 2.3. END ---------------------------------------------------------------------

# 2.4. APPLY CHANGES -----------------------------------------------------------

util-nginx-apply;

# 2.4. END ---------------------------------------------------------------------

# 2.4. APPLY CHANGES -----------------------------------------------------------

server-nginx restart;

# 2.4. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++