#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="SETUP";
TASK_NAME="DEFAULT LANDING PAGE";

_REPO_DEFAULT="git@github.com:traaidmark/default.habitat.traaidmark.com.git"

export DOMAIN="default"
export SITE_WWW="$DOMAIN/www";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# 2.1. CREATE SITE -------------------------------------------------------------

echo "- Create site";
[ ! -d $_SITES/$DOMAIN ] && git clone $_REPO_DEFAULT $_SITES/$DOMAIN &&  echo "-- ✅ Cloned default page repo";

# 2.1. END ---------------------------------------------------------------------

# 2.2. ADD TO WWW --------------------------------------------------------------

[ ! -d $_WWW/$DOMAIN ] && ln -s $_SITES/$SITE_WWW $_WWW/$DOMAIN  &&  echo "-- ✅ Linked www to server";

# 2.2. END ---------------------------------------------------------------------

# 2.3. REGISTER SITE -----------------------------------------------------------

util-nginx-register-default;

# 2.3. END ---------------------------------------------------------------------

# 2.4. APPLY CHANGES -----------------------------------------------------------

util-nginx-apply;

# 2.4. END ---------------------------------------------------------------------

# 2.4. APPLY CHANGES -----------------------------------------------------------

server-nginx restart;

# 2.4. END ---------------------------------------------------------------------

echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++