#! /bin/bash

# 1. REGISTER SITE +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "Registering Nginx Site: Static: $1"
echo ""
echo "---"
echo ""

nginx_path="$PWD/sites-available"
url=$1.dev.traaidmark.com;

echo "server {
  listen 80;
  listen [::]:80;

  root /var/www/static/$url/www;
  index index.html;

  server_name $url;

  location / {
    try_files \$uri \$uri/ =404;
  }
}" > $nginx_path/$url.conf

echo ""
echo "---"
echo ""

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++