#! /bin/bash

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="NGINX WORDPRESS CONFIG";
TASK_NAME=$DOMAIN;

CONF_PATH="$SITES/$DOMAIN.conf"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# CREATE STRUCTURE IF NEEDED

echo "- Check NGINX conf file:";
echo "-";
if [ -d $CONF_PATH ]
then
  rm -rf $CONF_PATH && echo "- ✅ Removed existing conf file";
fi

echo "- Create $DOMAIN conf file:";
echo "-";

echo "server {
  listen 80;
  listen [::]:80;

  server_name $DOMAIN;

  root /var/www/php8/wp/$url.dev.traaidmark.com/www;
  index index.php;
  
  server_tokens off;
  
  location / {
    # First attempt to serve request as file, then    
    # as directory, then fall back to displaying a 404.    
    try_files \$uri \$uri/ /index.php?\$args;
  }

  # pass the PHP scripts to FastCGI server listening on wordpress:9000  
  
  location ~ \.php$ {    
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass habitat-php:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
  }
}" > $CONF_PATH && echo "- ✅ Created conf file";

echo ""
echo "= $TASK_TYPE COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
