#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

TASK_TYPE="SERVER";
TASK_NAME="NGINX";

ACTION="$1"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "+"
echo "+ $TASK_TYPE: $TASK_NAME"
echo "+"
echo ""

# 2.1. START -------------------------------------------------------------------

if [ $ACTION = "start" ]
then
  echo "- Start NGINX";
  sudo systemctl start nginx && echo "-- ✅ Started";
fi

# 2.1. END ---------------------------------------------------------------------

# 2.2. RESTART -----------------------------------------------------------------

if [ $ACTION = "restart" ]
then
  echo "- Restart NGINX";
  sudo systemctl restart nginx && echo "-- ✅ Restarted";
fi

# 2.2. END ---------------------------------------------------------------------

# 2.3. RESTART -----------------------------------------------------------------

if [ $ACTION = "stop" ]
then
  echo "- Stop NGINX";
  sudo systemctl stop nginx && echo "-- ✅ Stopped";
fi

# 2.3. END ---------------------------------------------------------------------





echo ""
echo "= $TASK_NAME COMPLETE"

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 3. POST CALLS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

nginx-make-default-site;

# 3. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++