#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"

# $TYPE
# $TYPE_PATH
# $DOMAIN
# $PROJECT_PATH
# $PROJECT_WWW
# $PROJECT_MODE
# $PROJECT_REPO

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

DIR_WORKBOOK="$PROJECT_PATH/_workbook";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. GLOBAL FOLDERS ----------------------------------------------------------

echo "- Verify clean project";

[ -d $PROJECT_PATH ] && rm -rf $PROJECT_PATH && echo "-- ✅ Removed $PROJECT_PATH";

# 2.1. END ---------------------------------------------------------------------

# 2.1. GLOBAL FOLDERS ----------------------------------------------------------

echo "- Create Project";

if [ $PROJECT_MODE = "local" ]
then
  echo "- 🤠 Creating local only project.";

  [ ! -d $PROJECT_PATH ] && mkdir $PROJECT_PATH && echo "-- ✅ Create $PROJECT_PATH";
  [ ! -d $DIR_WORKBOOK ] && mkdir $DIR_WORKBOOK && echo "-- ✅ Create $DIR_WORKBOOK";
  [ ! -d $PROJECT_WWW ] && mkdir $PROJECT_WWW && echo "-- ✅ Create $PROJECT_WWW";
  
else 
  echo "- 🤠 Creating project from new repository";
  git clone $PROJECT_REPO $PROJECT_PATH;
fi

# 2.1. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++