#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# Available Local Vars
#
# ENV="$1"
# STACK="$2"
# DOMAIN="$NAME.$ENV.traaidmark.com"
# SITE_PATH="$_SITES/$DOMAIN"
# SITE_ROOT="$SITE_PATH/www"
# SITE_MODE="Local"
# SITE_REPO="$REPO"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

DIR_WORKBOOK="$SITE_PATH/_workbook";
DIR_BACKUPS="$SITE_PATH/_backups";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. VERIFY SITE -------------------------------------------------------------



# 2.1. END ---------------------------------------------------------------------

# 2.2. CREATE SITE -------------------------------------------------------------

echo "- Create Project";

if [ $SITE_MODE = "Local" ]
then
  echo "- 🤠 Creating local only project.";

  [ ! -d $SITE_PATH ] && mkdir $SITE_PATH && echo "-- ✅ Create $SITE_PATH";
  
else 
  echo "- 🤠 Creating project from new repository";
  git clone $SITE_REPO $SITE_PATH && echo "-- ✅ Cloned site into $SITE_PATH";
fi

# 2.2. END ---------------------------------------------------------------------

# 2.3. SCAFFOLD SITE DIRS ------------------------------------------------------

echo "- Scaffold Project Directories";


if [ $STACK = "wordpress" ]
then
  # ASSETS DIRECTORY
  if [ ! -d $DIR_BACKUPS ]
  then
  [ ! -d $DIR_BACKUPS ] && mkdir $DIR_BACKUPS && touch .gitignore && echo "-- ✅ Create $DIR_BACKUPS";
  else 
  echo "-- 🤠 $DIR_BACKUPS exists - skipping";
  fi
  # ASSETS / DATABASE DIRECTORY
  if [ ! -d $DIR_BACKUPS/db ]
  then
  [ ! -d $DIR_BACKUPS/db ] && mkdir $DIR_BACKUPS/db && touch .gitignore && echo "-- ✅ Create $DIR_BACKUPS/db";
  else 
  echo "-- 🤠 $DIR_BACKUPS/db exists - skipping";
  fi
  # ASSETS / CONF DIRECTORY
  if [ ! -d $DIR_BACKUPS/config ]
  then
  [ ! -d $DIR_BACKUPS/config ] && mkdir $DIR_BACKUPS/config && touch .gitignore && echo "-- ✅ Create $DIR_BACKUPS/config";
  else 
  echo "-- 🤠 $DIR_BACKUPS/config exists - skipping";
  fi
  # ASSETS / MISC DIRECTORY
  if [ ! -d $DIR_BACKUPS/misc ]
  then
  [ ! -d $DIR_BACKUPS/misc ] && mkdir $DIR_BACKUPS/misc && touch .gitignore && echo "-- ✅ Create $DIR_BACKUPS/misc";
  else 
  echo "-- 🤠 $DIR_BACKUPS/misc exists - skipping";
  fi
fi

if [ ! -d $SITE_ROOT ]
then
  [ ! -d $SITE_ROOT ] && mkdir $SITE_ROOT && echo "-- ✅ Create $SITE_ROOT";
else 
  echo "-- 🤠 $SITE_ROOT exists - skipping";
fi

# 2.3. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++