#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# Available Local Vars
#
# ENV="$1"
# STACK="$2"
# DOMAIN="$NAME.$ENV.traaidmark.com"
# SITE_PATH="$_SITES/$DOMAIN"
# SITE_ROOT="$SITE_PATH/www"
# SITE_MODE="Local"
# SITE_REPO="$REPO"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

CONFIG_FILE="$SITE_ROOT/wp-config.php"
BACKUP_FILE="$SITE_PATH/_backups/config/wp-config-dev.php"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. CREATE CONFIG -----------------------------------------------------------

echo "- Install Wordpress";

wp core install --path="$SITE_ROOT" --url="http://$DOMAIN" --title="$NAME" --admin_user="$_WP_ADMIN_USER" --admin_password="$_WP_ADMIN_PASSWORD" --admin_email="$_WP_ADMIN_EMAIL" --skip-email && echo "-- ✅ Wordpress Installed";

# 2.1. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++