#! /bin/bash

# Available system vars:
# WWW="$HOME/data/www"
# BOX="$HOME/box"
# SITES="$HOME/data/sites"

# $TYPE
# $TYPE_PATH
# $DOMAIN
# $PROJECT_PATH
# $PROJECT_WWW
# $PROJECT_MODE
# $PROJECT_REPO

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

DIR_WORKBOOK="$PROJECT_PATH/_workbook";
DIR_CACHE="$TYPE_PATH/_cache";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. COPY WORDPRESS CACHE ----------------------------------------------------

echo "- Copy Wordpress Cache";

cp -r $DIR_CACHE/. $PROJECT_WWW/ && echo "-- ✅ Copied Wordpress from Cache";

# 2.1. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++