#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# Available Local Vars
#
# ENV="$1"
# STACK="$2"
# DOMAIN="$NAME.$ENV.traaidmark.com"
# SITE_PATH="$_SITES/$DOMAIN"
# SITE_ROOT="$SITE_PATH/www"
# SITE_MODE="Local"
# SITE_REPO="$REPO"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

DIR_META="$_BOX/dev-meta"
DIR_WORKBOOK="$PROJECT_PATH/_workbook";
DIR_BOX_GENERAL_DEV="$BOX/general/dev";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. GLOBAL FOLDERS ----------------------------------------------------------

echo "- Apply dev meta";

cp -r $DIR_META/. $SITE_ROOT && echo "-- ✅ Copied dev meta files";

# 2.1. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++