#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

CONF_PATH="$_SITE_CONF/$DOMAIN"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo "- Register $DOMAIN in NGINX:";
if [ -d $CONF_PATH ]
then
  rm -rf $CONF_PATH && echo "-- ✅ Removed existing conf file";
fi

echo "- Create $DOMAIN conf file:";

echo "server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name $DOMAIN;

  root /var/www/$DOMAIN;

  index index.html;
  
  location / {
    try_files \$uri \$uri/ =404;
  }
}" > $CONF_PATH && echo "-- ✅ Created conf file";

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++