#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# Available Local Vars
#
# ENV="$1"
# STACK="$2"
# DOMAIN="$NAME.$ENV.traaidmark.com"
# SITE_PATH="$_SITES/$DOMAIN"
# SITE_ROOT="$SITE_PATH/www"
# SITE_MODE="Local"
# SITE_REPO="$REPO"
#
# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

CONFIG_FILE="$SITE_ROOT/wp-config.php"
BACKUP_FILE="$SITE_PATH/_backups/config/wp-config-dev.php"

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. CREATE CONFIG -----------------------------------------------------------

echo "- Create Wordpress config file";

wp config create --path="$SITE_ROOT" --dbname="trm-client-wp-$NAME-db" --dbuser=$_DATABASE_USER --dbpass=$_DATABASE_PASSWORD --dbhost="localhost" && echo "-- ✅ Config file created";

# 2.1. END ---------------------------------------------------------------------

# 2.2. CREATE CONFIG -----------------------------------------------------------

echo "- Backup Wordpress config file";

cp $CONFIG_FILE $BACKUP_FILE && echo "-- ✅ Config backed up to _backups dir";

# 2.2. END ---------------------------------------------------------------------





# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++