#! /bin/bash

# Available system vars:
#
# _WWW="$_R/www"
# _WWW_DEV="$_R/www/dev"
# _WWW_PROD="$_R/www/prod"
#
# _SITES="$_R/sites"
# _SITE_CONF="$_R/site-conf"
#
# _BOX="$_R/.box"
# _BIN="$_R/.bin"
# _CACHE="$_R/.cache"
#
# Available Local Vars
#
# DOMAIN="$NAME.$ENV.traaidmark.com"
# SITE_PATH="$_SITES/$DOMAIN"

# 1. VARIABLES +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

MSG="$1";

# 1. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2. SCRIPT ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# 2.1. VERIFY SITE -------------------------------------------------------------

echo "- Commit to repository";

git add $SITE_PATH . && git commit $SITE_PATH -m "Habitat Server: $MSG" && git push $SITE_PATH origin && echo "-- ✅ Committed and pushed repository to origin";

# 2.1. END ---------------------------------------------------------------------

# 2. END +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++